### ISSUE TITLE
timeout in docs says "seconds", but is actually msecs

### ISSUE THREAD

**Issue by justingrant** [linusg/libjs-test262#35]
According to CLI usage docs: 
```
--timeout TIMEOUT     timeout for each test run in seconds (defaults to 10)
```

But when actually running tests, it seems that the timeout CLI argument is actually denominated in milliseconds. To repro:

* Add code to a test that will cause it to pause for a long time (e.g. infinite loop or a debugger statement if running in a debugger)
* Run tests using default timeout value
* Now run tests again using `--timeout 10`

Expected: no difference; a paused or hung test is killed after 10 seconds in both cases
Actual: using `--timeout 10`, tests are killed almost instantaneously (I assume after 10ms)

**Comment by IdanHo** [comment]
I can't reproduce this, can you go through your steps and run it with `-v` to make sure it is actually failing due to the timeout and not some other issue?

**Comment by linusg** [comment]
The timeout argument value is eventually passed to `subprocess.run()` (unmodified), which in turn passes it to `Popen.communicate()`, which is [documented](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate) as:

> If the process does not terminate after timeout seconds, a `TimeoutExpired` exception will be raised. Catching this exception and retrying communication will not lose any output.

So the current implementation should behave correctly. I agree with Idan's suggestion to check the verbose output to ensure that there's not something else failing along the way (JS exception, or an issue with the `libjs-test262-runner` invocation before that).

**Comment by justingrant** [comment]
> an issue with the `libjs-test262-runner` invocation before that

Hmmm, I'll take a look. My apologies for not checking upstream libs first!

**Comment by justingrant** [comment]
> > an issue with the `libjs-test262-runner` invocation before that
> 
> Hmmm, I'll take a look. My apologies for not checking upstream libs first!

Yep, it was upstream. `test262-harness` uses msecs for its timeout. So sorry for the false alarm. Closing.
